version: '2'
services:
  web:
    container_name: sample_web
    image: sample/web
    build: web
    env_file:
      - "commons.env"
    restart: always
    #volume:
    #  -
    ports:
      - "10080:80"
    networks:
      sample:
        ipv4_address: 172.28.5.2
    links:
      - app:tomcat
  #rdb:
  app:
    container_name: sample_app
    build: app
    env_file:
      - "commons.env"
    #volume:
    #  -
    restart: always
    ports:
      - "8080:8080"
      - "8009:8009"
    networks:
      sample:
        ipv4_address: 172.28.5.4
  #batch:
  maven:
    container_name: sample_maven
    build: maven
    volumes:
      - ./maven/app:/opt/app
    stdin_open: true
    tty: true
    networks:
      sample:
        ipv4_address: 172.28.5.6

networks:
  sample:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16
          ip_range: 172.28.5.0/24
          gate_way: 172.28.5.1
