version: '2'
services:
  app:
    container_name: sample_app
    build: ./app
    volumes:
      - ./app:/opt/app
      - ./conf:/usr/share/maven/conf
    stdin_open: true
    tty: true
    networks:
      sample:
        ipv4_address: 172.28.5.2
  tomcat:
    container_name: sample_tomcat
    build: ./tomcat
    env_file:
      - "commons.env"
    #volume:
    #  -
    restart: always
    ports:
      - "8080:8080"
      - "8009:8009"
    networks:
      sample:
        ipv4_address: 172.28.5.4
  httpd:
    container_name: sample_httpd
    build: ./httpd
    env_file:
      - "commons.env"
    restart: always
    #volume:
    #  -
    ports:
      - "10080:80"
    networks:
      sample:
        ipv4_address: 172.28.5.5
    links:
      - tomcat:tomcat

networks:
  sample:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16
          ip_range: 172.28.5.0/24
          gate_way: 172.28.5.1
